# Generated by Django 6.0.2 on 2026-03-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("systemapp", "0002_newslettersubscriber_workerprofile_approved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vetprofile",
            name="license_document",
            field=models.FileField(blank=True, null=True, upload_to="vet_licenses/"),
        ),
        migrations.AlterField(
            model_name="vetprofile",
            name="license_number",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]

