# Generated by Django 6.0.2 on 2026-03-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("systemapp", "0003_vetprofile_license_document_and_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="vetprofile",
            name="location",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]

